### PR TITLE
Draft DOM Overlay spec for discussion

### PR DESCRIPTION
**Pull request by klausw**

### CODE REVIEW

**Comment by klausw** [comment]
HTML version is at https://klausw.github.io/dom-overlays/index.html

**Comment by klausw** [comment]
/agenda Get feedback on draft DOM Overlay spec

@toji @NellWaliczek @Manishearth FYI. The spec is still a bit rough around the edges, but I wanted to give the CG a chance to look at it.

The algorithms are a bit ad-hoc at the moment. If people agree with the overall approach, we'd need to see how to best integrate this with the core WebXR spec, i.e. by adding a hopefully-small set of integration points such as state booleans that this module can refer to.

Known gaps include details around error conditions such as not supplying the required root element, and it needs more details about pointer visualization for headset implementations. 

The "event handling for cross-origin content" section is based on my assumption that we should follow similar semantics as a cross-origin iframe on a 2D web page. The 2D behavior seems to be that input details including mouse movement data goes either to the cross-origin iframe or to the outer page, but never to both. However, I haven't found any specific documentation that lists this as an actual requirement. If people think this is overly paranoid, please let me know. FWIW, I have WIP implementation in Chrome that matches that description, I had wanted to make sure that this approach is feasible.

**Comment by RangerMauve** [comment]
What is the use case guiding this feature?

**Comment by RangerMauve** [comment]
Also, may I ask why the content is being positioned by the user agent rather than the document?

**Comment by klausw** [comment]
> What is the use case guiding this feature?

Did you see the overview in https://github.com/immersive-web/dom-overlays/blob/master/explainer.md ?

https://github.com/immersive-web/dom-overlays/blob/master/design-choices.md has some additional background about design decisions and links to previous discussions.

> Also, may I ask why the content is being positioned by the user agent rather than the document?

Document/application-placed content is intended to be covered by the separate "Layers" proposal, see https://github.com/immersive-web/layers for that. Ideally, user agents would support both, potentially sharing underlying technologies where appropriate.

A primary use case for the DOM Overlay proposal is to enable content that works across a variety of form factors, including handheld AR on a smartphone and head-mounted displays, and that's in conflict with having the content being positioned by the application. For example, a UI based on an app-placed floating quad in space that's designed to be used with 6DoF controllers in an HMD is very likely to be difficult to use on a smartphone.

**Comment by RangerMauve** [comment]
Ah! I totally missed the explainer. Thank you!

So just to confirm, this would be on the roadmap for figuring out how to render the DOM overlay in stereoscopic rendering modes like VR / AR headsets, as well, right?

**Comment by klausw** [comment]
@RangerMauve yes, showing the DOM overlay in a HMD is in scope for this proposal, for example rendering it as a floating quad in space. However, due to the lack of control over placement and other technical restrictions (see the "design choices" doc), this is primarily intended as a way to provide cross-form-factor compatibility. A HMD-centric application would likely get better results from using DOM layers (as opposed to this single DOM overlay).

**Comment by klausw** [comment]
Updated rendered version at https://klausw.github.io/dom-overlays/index.html . (I've configured https://github.com/tobie/pr-preview , but looks like that doesn't work retroactively for existing pull requests?)

**Comment by bialpio** [comment]
Looks good to me!

**Comment by klausw** [comment]
This is now live at https://immersive-web.github.io/dom-overlays/ , thanks to @toji for setting up the bikeshed generation infrastructure. Of course, this doesn't mean to imply it's done, but I think it's easier to use PRs against the existing version going forward. Please open issues or PRs in case of feedback or change requests.

**Pull request merged**
